import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthProvider from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className + "w-full h-screen"}>
          <nav className="flex space-x-4">
            <Link
              href={"/chat"}
              className="bg-zinc-800 hover:bg-zinc-700 hover:border-l-2 px-4 py-1 m-1"
            >
              Chat
            </Link>
            <Link
              href={"/deshboard"}
              className="bg-zinc-800 hover:bg-zinc-700 hover:border-l-2 px-4 py-1 m-1"
            >
              Deshboard
            </Link>
          </nav>
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
